# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
