# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('portrait', models.ImageField(null=True, upload_to='')),
                ('birth', models.DateField(null=True)),
                ('register_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
